// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aklakiccvzjhwvqgrceg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbGFraWNjdnpqaHd2cWdyY2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTc5NDgsImV4cCI6MjA2ODIzMzk0OH0.48G16KXXaUIM3wWhhZRKzRb30zQP7eO7SeVBRDAobQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});